#IF YOURE WONDERING WHERE ALL THE NON-CONSCRIPT JOBS WENT
#JUST RE-ENABLE THEM AND SET editorHidden: false
#YOU'RE WELCOME
# .2 - 2025

- type: department
  id: Logistics
  name: department-Logistics
  description: department-Cargo-description
  color: "#A46106"
  roles:
  - CargoTechnician
  - Quartermaster
  - SalvageSpecialist
  - MailCarrier
  editorHidden: true

- type: department
  id: Civilian
  name: department-Civilian
  description: department-Civilian-description
  color: "#9FED58"
  weight: 5
  roles:
  - Bartender
  - Botanist
  - Boxer
  - Chef
  - Clown
  - HeadOfPersonnel
  - Janitor
  - Mime
  - Musician
  - Passenger
  - Reporter
  - Visitor
  - Zookeeper
  - ServiceWorker
  - MartialArtist
  - Prisoner
  - Gladiator
  editorHidden: true

- type: department
  id: CentralCommand
  name: department-CentralCommand
  description: department-CentralCommand-description
  color: "#0c344d"
  roles:
  - CentralCommandOfficial
  - CBURN
  - ERTLeader
  - ERTChaplain
  - ERTJanitor
  - ERTMedical
  - ERTSecurity
  - ERTEngineer
  - DeathSquad
  editorHidden: true
  weight: 120
>>>>>>> parent of 293820ea6d (Реверт 5)

- type: department
  id: Command
  description: department-Command-description
  color: "#334E6D"
  roles:
  - CentralCommandOfficial
  - HeadOfPersonnel # Not shown but needed here for playtime
  - HeadOfSecurity # Not shown but needed here for playtime
#  - ChiefMedicalOfficer
  primary: false
  weight: 100
  editorHidden: true
<<<<<<< HEAD
=======

- type: department
  id: Dignitary
  name: department-Dignitary
  description: department-Dignitary-description
  color: "#33FE6D"
  roles:
  - BlueshieldOfficer
  - NanotrasenRepresentative
  - Magistrate
  primary: false
  weight: 101
  editorHidden: true
>>>>>>> parent of 293820ea6d (Реверт 5)

- type: department
  id: Engineering
  description: department-Engineering-description
  color: "#EFB341"
  weight: -94
  primary: false
  editorHidden: true

- type: department
  id: Medical
  description: department-Medical-description
  color: "#52B4E9"
<<<<<<< HEAD
  weight: -93
=======
  roles:
  - Chemist
  - ChiefMedicalOfficer
  - MedicalDoctor
  - MedicalIntern
  - Psychologist
  - Paramedic
  - SeniorPhysician
  - MedicalBorg
>>>>>>> parent of 293820ea6d (Реверт 5)
  editorHidden: true

- type: department
  id: Security
  description: department-Security-description
  color: "#DE3A3A"
  weight: 20
  roles:
  - Detective
  - HeadOfSecurity
  - SecurityCadet
  - SecurityOfficer
  - Warden
<<<<<<< HEAD
=======
  - PrisonGuard
  - Brigmedic
>>>>>>> parent of 293820ea6d (Реверт 5)
  editorHidden: true

- type: department
  id: Epistemics
  description: department-Epistemics-description
  color: "#D381C9"
<<<<<<< HEAD
  weight: -92
  primary: false
=======
  roles:
  - ResearchDirector
  - SeniorResearcher
  - Scientist
  - ResearchAssistant
  - Chaplain
  - ForensicMantis
  - Librarian
  - Roboticist
  editorHidden: true

- type: department
  id: Silicon
  name: department-Silicon
  description: department-Silicon-description
  color: "#D381C9"
  roles:
  - Borg
  - StationAi
>>>>>>> parent of 293820ea6d (Реверт 5)
  editorHidden: true

- type: department
  id: Specific
  description: department-Specific-description
  color: "#9FED58"
  weight: -91
  primary: false
  editorHidden: true
<<<<<<< HEAD

- type: department
  id: NCWL
  description: department-NCWL-description
  color: "#FFD580"
  weight: 100
  roles:
  - CommandantNCWL
  - KommissarNCWL
  - MVDGruntNCWL
  - FleetkapitanNCWL
  - PartisanNCWL
  - DirectorNCWL
  - DoctorNCWL
  - WorkerOverbossNCWL
  - DockhandNCWL
  - IndustryTaskmasterNCWL
  - ArtificerNCWL
  - WorkerNCWL
  editorHidden: false

- type: department
  id: NCSP
  description: department-NCSP-description
  color: "#DC143C"
  weight: 90
  roles:
  - RingleaderNCSP
  - LieutenantNCSP
  - InfanteerNCSP
  - TechnicianNCSP
  - CoordinatorNCSP
  - RipperdocNCSP
  - TraumasecNCSP
  - OperativeNCSP
  - IntelligenceOfficerNCSP
  - CyberdawnTechNCSP
  - ForemanNCSP
  - ShipbreakerNCSP
  editorHidden: false

- type: department
  id: DSM
  description: department-DSM-description
  color: "#684871"
  weight: 85
  roles:
  - FreeholderDSM
  - LevymanDSM
  - KnightDSM
  - RitterDSM
  - WealthDSM
  - ForemanDSM
  - ScribeDSM
  - TemplarDSM
  - SurgeonDSM
  - LaborDSM
  - CourtierDSM
  - AdjutantDSM
  - GovernorDSM
  - AdvocatusDSM
  - ArchmaesterDSM
  editorHidden: false

- type: department
  id: SRM
  description: department-SRM-description
  color: "#4a6741"
  weight: 80
  roles:
  - TenderSRM
  - AcolyteSRM
  - HunterSRM
  - MontagneSRM
  - OverseerSRM
  editorHidden: false # i just like to see them for the numbers , SPCR 2025

- type: department
  id: SHI
  description: department-SHI-description
  color: "#4a6741"
  weight: 75
  roles:
  - ExecutiveSHI
  - BoardSHI
  - HighsecSHI
  - CorpsecSHI
  - EmployeeSHI
  - MedtechSHI
  - BoardHRSHI
  - HosSHI
  editorHidden: false

- type: department
  id: CMM
  description: department-CMM-description
  color: "#5191e0"
  weight: 70
  roles:
  - OrdnancemanCMM
  - MachinistCMM
  - PhysicianCMM
  - MinutemanCMM
  - WatchmasterCMM
  - DeputyMarshalCMM
  - MarshalCMM
  editorHidden: true

- type: department
  id: TAP
  description: department-TAP-description
  color: "#50c878"
  weight: 55
  roles:
  # - ProphetTAP #commented the rest until TAP comes back .2 | 2025
  # - AcolyteTAP
  # - TinkererTAP
  # - TechminerTAP
  # - HangarTechTAP
  - Antiquarian
  - BeltrunnerTAP
  - DraugrTAP
  - ServileTAP
  editorHidden: false

- type: department
  id: ATH
  description: department-ATH-description
  color: "#ffffed"
  weight: 40
  roles:
  - KommandantATH
  - LeutnantATH
  - KanoneerATH
  - SoldatATH
  - SanitatATH
  - StewardATH
  - OberartzATH
  - LogistatATH
  - HandelsATH
  - ForscherATH
  - ChirurgeonATH
  - VorarbeiterATH
  - ArbeiterATH
  editorHidden: true # i just like to see them for the numbers , SPCR 2025

  # CONSCRIPT

- type: department
  id: NCWL-W
  description: department-NCWL-description
  color: "#FFD580"
  weight: 11
  roles:
  - ConscriptLeaderNCWL
  - ConscriptOfficerNCWL
  - ConscriptSniperNCWL
  - ConscriptGunnerNCWL
  - ConscriptDoctorNCWL
  - ConscriptShotgunNCWL
  - ConscriptSubmachinegunNCWL
  - ConscriptRiflemanNCWL
  - ConscriptCadetNCWL
  - ConscriptShipCaptainNCWL
  - ConscriptShipCrewNCWL
  editorHidden: true

- type: department
  id: DSM-W
  description: department-DSM-description
  color: "#684871"
  weight: 10
  roles:
  - ConscriptLeaderDSM
  - ConscriptOfficerDSM
  - ConscriptSniperDSM
  - ConscriptGunnerDSM
  - ConscriptDoctorDSM
  - ConscriptShotgunDSM
  - ConscriptSubmachinegunDSM
  - ConscriptRiflemanDSM
  - ConscriptCadetDSM
  - ConscriptShipCaptainDSM
  - ConscriptShipCrewDSM
  editorHidden: true
=======
>>>>>>> parent of 293820ea6d (Реверт 5)
